### PR TITLE
Migrated code from JS to TS and runtime from Node to Bun

### LINKED ISSUE #14: Migrate to Typescript
idk why I didnt use typescript to begin with. If we do this we should move this to a bun project because typescript runs out of the box in bun.

### PR DESCRIPTION
**Pull request by kofta999**
Fixes #14

Finished working on the code but sadly couldn't fully test it as I couldn't set Ord up.
So please try it out and tell me if anything.

### CODE REVIEW

**Comment by elocremarc** [comment]
Sweet I will check it out. Do you need help getting ord running? You don't need to have bitcoin blocks or even the ord index to run OPM because it uses regtest. You can just install the ord binary and you should be good to go.

https://github.com/ordinals/ord#installation

**Review by elocremarc — APPROVED** [review]
Looks good! Nice work gonna merge it.

**Comment by kofta999** [comment]
Thanks! Glad I could help.

**Comment by elocremarc** [comment]
@kofta999 stuff started to break after this PR see issues #21 and #22.

**Comment by kofta999** [comment]
> @kofta999 stuff started to break after this PR see issues #21 and #22.

Checked them out, if the issues in Bun, and you don't like ts-node, what about deno?
At very least it supports TS out of the box.

**Comment by elocremarc** [comment]
@kofta999 I was able to patch the issues by having converting those scripts to be run as shell scripts. So everything seems to be working now. Could look into this at a later point if I wanna run those with bun.

**Pull request merged**
